add bg link&&format scripts

diff --git a/.local/bin/ext b/.local/bin/ext
--- a/.local/bin/ext
+++ b/.local/bin/ext
@@ -1,39 +1,39 @@
 #!/bin/sh
 
 while getopts "hc" o; do case "${o}" in
-  c) extracthere="True" ;;
-  *) prinf "Options:\\n   -c: Extract archive into current directory rather than a new one.\\n" && exit 1 ;;
-esac done
+	c) extracthere="True" ;;
+	*) prinf "Options:\\n   -c: Extract archive into current directory rather than a new one.\\n" && exit 1 ;;
+	esac done
 
 if [ -z "$extracthere" ]; then
-  archive="$(readlink -f "$*")" &&
-  directory="$(echo "$archive" | sed 's/\.[^\/.]*$//')" &&
-  mkdir -p "$directory" &&
-  cd "$directory" ||exit 1
+	archive="$(readlink -f "$*")" &&
+		directory="$(echo "$archive" | sed 's/\.[^\/.]*$//')" &&
+		mkdir -p "$directory" &&
+		cd "$directory" || exit 1
 else
-  archive="$(readlink -f "$(echo "$*" | cut -d' ' -f2)" 2>/dev/null)"
+	archive="$(readlink -f "$(echo "$*" | cut -d' ' -f2)" 2>/dev/null)"
 fi
 
 [ -z "$archive" ] && printf "Give archive to extract as argument.\\n"
 
 if [ -f "$archive" ]; then
-  case "$archive" in
-    *.tar.bz2|*tbz2) bsdtar -xf "$archive" ;;
-		*.tar.xz) bsdtar -xf "$archive" ;;
-		*.tar.gz|*.tgz) bsdtar -xf "$archive" ;;
-		*.tar.zst) bsdtar -xf "$archive" ;;
-		*.tar) bsdtar -xf "$archive" ;;
-		*.lzma) unlzma "$archive" ;;
-		*.bz2) bunzip2 "$archive" ;;
-		*.rar) unrar x -ad "$archive" ;;
-		*.gz) gunzip "$archive" ;;
-		*.zip) unzip "$archive" ;;
-		*.Z) uncompress "$archive" ;;
-		*.7z) 7z x "$archive" ;;
-		*.xz) unxz "$archive" ;;
-		*.exe) cabextract "$archive" ;;
-		*) printf "extract: '%s' - unknown archive method\\n" "$archive" ;;
-  esac
+	case "$archive" in
+	*.tar.bz2 | *tbz2) bsdtar -xf "$archive" ;;
+	*.tar.xz) bsdtar -xf "$archive" ;;
+	*.tar.gz | *.tgz) bsdtar -xf "$archive" ;;
+	*.tar.zst) bsdtar -xf "$archive" ;;
+	*.tar) bsdtar -xf "$archive" ;;
+	*.lzma) unlzma "$archive" ;;
+	*.bz2) bunzip2 "$archive" ;;
+	*.rar) unrar x -ad "$archive" ;;
+	*.gz) gunzip "$archive" ;;
+	*.zip) unzip "$archive" ;;
+	*.Z) uncompress "$archive" ;;
+	*.7z) 7z x "$archive" ;;
+	*.xz) unxz "$archive" ;;
+	*.exe) cabextract "$archive" ;;
+	*) printf "extract: '%s' - unknown archive method\\n" "$archive" ;;
+	esac
 else
-  printf "File \"%s\" not found.\\n" "$archive"
+	printf "File \"%s\" not found.\\n" "$archive"
 fi
